### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by tsevigny** [jczic/MicroMLP#6]
I get this error;

Traceback (most recent call last):
  File "main.py", line 19, in <module>
  File "microMLP.py", line 771, in LearnExamples
IndexError: list index out of range

when I run the example code, "Using MicroMLP to learn the XOr problem (with hyperbolic tangent)".
The RandomFloat() seems to generate an idx that is out of range of the 4 examples supplied.

Not sure what I am doing wrong.

**Comment by Andre-cmd-rgb** [comment]
same
